### ISSUE TITLE
Error: OAuth authentication requires session support

### ISSUE THREAD

**Issue by macbroadcast** [gravityonmars/Balloons.IO#111]
hi, installed Balloons.IO on my site http://chat.let.de , but it seems the express version is deprecated , when i want to login with twitter, i got this error:

```Error: OAuth authentication requires session support
    at Strategy.OAuthStrategy.authenticate (/root/Balloons.IO/node_modules/passport-twitter/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth.js:102:41)
    at Strategy.authenticate (/root/Balloons.IO/node_modules/passport-twitter/lib/passport-twitter/strategy.js:82:40)
    at attempt (/root/Balloons.IO/node_modules/passport/lib/passport/middleware/authenticate.js:243:16)
    at Passport.authenticate (/root/Balloons.IO/node_modules/passport/lib/passport/middleware/authenticate.js:244:7)
    at callbacks (/root/Balloons.IO/node_modules/express/lib/router/index.js:161:37)
    at param (/root/Balloons.IO/node_modules/express/lib/router/index.js:135:11)
    at pass (/root/Balloons.IO/node_modules/express/lib/router/index.js:142:5)
    at Router._dispatch (/root/Balloons.IO/node_modules/express/lib/router/index.js:170:5)
    at Object.router (/root/Balloons.IO/node_modules/express/lib/router/index.js:33:10)
    at Context.next (/root/Balloons.IO/node_modules/express/node_modules/connect/lib/proto.js:190:15)```

signing in with facebook gives no error but it does not work ether. 

Any help ? Thanks

**Comment by cristiandouce** [comment]
Check the passport dependencies versions. They must be outdated and some things may have change.

**Comment by macbroadcast** [comment]
Thanks @cristiandouce , i´ve updated the express and passport (twitter+facebook) dependecies, but still got an error, guess some portions of the code needs to be rewriten. :v:
